#          ___           ___            ___           ___           ___       ___           ___           ___     
#         /\__\         |\__\          /\  \         /\  \         /\__\     /\  \         /\__\         /\  \    
#        /:/  /         |:|  |        /::\  \       /::\  \       /:/  /    /::\  \       /::|  |       /::\  \   
#       /:/__/          |:|  |       /:/\:\  \     /:/\:\  \     /:/  /    /:/\:\  \     /:|:|  |      /:/\:\  \  
#      /::\  \ ___      |:|__|__    /::\~\:\  \   /::\~\:\  \   /:/  /    /::\~\:\  \   /:/|:|  |__   /:/  \:\__\ 
#     /:/\:\  /\__\     /::::\__\  /:/\:\ \:\__\ /:/\:\ \:\__\ /:/__/    /:/\:\ \:\__\ /:/ |:| /\__\ /:/__/ \:|__|
#     \/__\:\/:/  /    /:/~~/___/ /:/ /\:\/:/  / \/_|::\/:/  / \:\  \    \/__\:\/:/  / \/__|:|/:/  / \:\  \ /:/  /
#          \::/  /    /:/  /     /:/ /  \::/  /     |:|::/  /   \:\  \        \::/  /      |:/:/  /   \:\  /:/  / 
#          /:/  /     \/__/      \/_/    \/__/      |:|\/__/     \:\  \       /:/  /       |::/  /     \:\/:/  /  
#         /:/  /                                   |:|  |        \:\__\     /:/  /        /:/  /       \::/__/   
#         \/__/                                     \|__|         \/__/     \/__/         \/__/                

source = ~/.config/hypr/modules/monitors.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/env_variables.conf
source = ~/.config/hypr/modules/permissions.conf
source = ~/.config/hypr/modules/look_and_feel.conf
source = ~/.config/hypr/modules/blur.conf
source = ~/.config/hypr/modules/animations.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/binds.conf
source = ~/.config/hypr/modules/windows_and_workspaces_rules.conf
source = ~/.config/hypr/modules/hypr-kinetic-scroll.conf

cursor {
no_hardware_cursors = 1
}
