#          ___           ___       ___           ___     
#         /\  \         /\__\     /\__\         /\  \    
#        /::\  \       /:/  /    /:/  /        /::\  \   
#       /:/\:\  \     /:/  /    /:/  /        /:/\:\  \  
#      /::\~\:\__\   /:/  /    /:/  /  ___   /::\~\:\  \ 
#     /:/\:\ \:|__| /:/__/    /:/__/  /\__\ /:/\:\ \:\__\
#     \:\~\:\/:/  / \:\  \    \:\  \ /:/  / \/_|::\/:/  /
#      \:\ \::/  /   \:\  \    \:\  /:/  /     |:|::/  / 
#       \:\/:/  /     \:\  \    \:\/:/  /      |:|\/__/  
#        \::/__/       \:\__\    \::/  /       |:|  |    
#         ~~            \/__/     \/__/         \|__|    

# https://wiki.hypr.land/Configuring/Variables/#blur
decoration {
    blur {
        enabled = true
        size = 7
        passes = 3
        ignore_opacity = true

        noise = 0.01
        contrast = 1.5  

        popups = true
        new_optimizations = true
    }
}

# Blur for swaync:
layerrule {
  name = swaync-blur
  match:namespace = ^(swaync-control-center|swaync-notification-window)$
  blur = on
  ignore_alpha = 0
  xray = 0
}

# Blur for rofi
layerrule {
  name = rofi-blur
  blur = on
  ignore_alpha = 0
  match:namespace = rofi
}

# Blur for wlogout
layerrule {
  name = wlogout-blur
  blur = on
  ignore_alpha = 0
  match:namespace = logout_dialog
}
