#          ___           ___           ___           ___           ___ 
#         /\  \         /\  \         /\  \         /\  \         /\__\
#        /::\  \       /::\  \       /::\  \       /::\  \       /:/  /
#       /:/\ \  \     /:/\:\  \     /:/\:\  \     /:/\:\  \     /:/  / 
#      _\:\~\ \  \   /:/  \:\  \   /::\~\:\  \   /:/  \:\  \   /:/  /  
#     /\ \:\ \ \__\ /:/__/ \:\__\ /:/\:\ \:\__\ /:/__/ \:\__\ /:/__/   
#     \:\ \:\ \/__/ \:\  \  \/__/ \/_|::\/:/  / \:\  \ /:/  / \:\  \   
#      \:\ \:\__\    \:\  \          |:|::/  /   \:\  /:/  /   \:\  \  
#       \:\/:/  /     \:\  \         |:|\/__/     \:\/:/  /     \:\  \ 
#        \::/  /       \:\__\        |:|  |        \::/  /       \:\__\
#         \/__/         \/__/         \|__|         \/__/         \/__/

plugin:kinetic-scroll:enabled = 1
plugin:kinetic-scroll:decel = 0.99
plugin:kinetic-scroll:friction = 0.002
plugin:kinetic-scroll:min_velocity = 0.6
plugin:kinetic-scroll:interval_ms = 8
plugin:kinetic-scroll:delta_multiplier = 1.25
plugin:kinetic-scroll:velocity_relevance_ms = 100
plugin:kinetic-scroll:min_sample_ms = 5
plugin:kinetic-scroll:max_velocity_samples = 5
plugin:kinetic-scroll:disable_in_browser = 1
plugin:kinetic-scroll:stop_on_target_change = 1

# Optional debug
plugin:kinetic-scroll:debug = 0
plugin:kinetic-scroll:stop_on_click = 0
plugin:kinetic-scroll:stop_on_focus = 0
