#                      ___           ___           ___           ___     
#          ___        /\__\         /\  \         /\__\         /\  \    
#         /\  \      /::|  |       /::\  \       /:/  /         \:\  \   
#         \:\  \    /:|:|  |      /:/\:\  \     /:/  /           \:\  \  
#         /::\__\  /:/|:|  |__   /::\~\:\  \   /:/  /  ___       /::\  \ 
#      __/:/\/__/ /:/ |:| /\__\ /:/\:\ \:\__\ /:/__/  /\__\     /:/\:\__\
#     /\/:/  /    \/__|:|/:/  / \/__\:\/:/  / \:\  \ /:/  /    /:/  \/__/
#     \::/__/         |:/:/  /       \::/  /   \:\  /:/  /    /:/  /     
#      \:\__\         |::/  /         \/__/     \:\/:/  /     \/__/      
#       \/__/         /:/  /                     \::/  /                 
#                     \/__/                       \/__/                  

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = fkeys:basic_13-24
    kb_rules =

    follow_mouse = 1

    accel_profile = flat

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        scroll_factor = 0.2
        disable_while_typing = no
        natural_scroll = true
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 4, horizontal, workspace
gesture = 3, up, float
gesture = 3, down, float

# 3 finger swiping for back and forward in browser
gesture = 3, left, dispatcher, exec, ~/.config/scripts/browser.sh
gesture = 3, right, dispatcher, exec, ydotool key Alt+Right

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-inpu>
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
