#          ___           ___           ___                       ___           ___           ___           ___     
#         /\__\         /\  \         /\__\          ___        /\  \         /\  \         /\  \         /\  \    
#        /::|  |       /::\  \       /::|  |        /\  \       \:\  \       /::\  \       /::\  \       /::\  \   
#       /:|:|  |      /:/\:\  \     /:|:|  |        \:\  \       \:\  \     /:/\:\  \     /:/\:\  \     /:/\ \  \  
#      /:/|:|__|__   /:/  \:\  \   /:/|:|  |__      /::\__\      /::\  \   /:/  \:\  \   /::\~\:\  \   _\:\~\ \  \ 
#     /:/ |::::\__\ /:/__/ \:\__\ /:/ |:| /\__\  __/:/\/__/     /:/\:\__\ /:/__/ \:\__\ /:/\:\ \:\__\ /\ \:\ \ \__\
#     \/__/~~/:/  / \:\  \ /:/  / \/__|:|/:/  / /\/:/  /       /:/  \/__/ \:\  \ /:/  / \/_|::\/:/  / \:\ \:\ \/__/
#           /:/  /   \:\  /:/  /      |:/:/  /  \::/__/       /:/  /       \:\  /:/  /     |:|::/  /   \:\ \:\__\  
#          /:/  /     \:\/:/  /       |::/  /    \:\__\       \/__/         \:\/:/  /      |:|\/__/     \:\/:/  /  
#         /:/  /       \::/  /        /:/  /      \/__/                      \::/  /       |:|  |        \::/  /   
#         \/__/         \/__/         \/__/                                   \/__/         \|__|         \/__/    
xwayland {

force_zero_scaling = true

}

# See https://wiki.hypr.land/Configuring/Monitors/
monitor= eDP-1, 1920x1200@60, 0x0, 1.33	
#monitor = eDP-1, disable
monitor= DP-1, 1920x1080@60, 1920x0, 1
monitor= DP-2, 1920x1080@60, 1920x0, 1
monitor= HDMI-A-1, 1920x1200@60, 3840x-500, 1, transform, 1

workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1

workspace = 4, monitor:HDMI-A-1
workspace = 5, monitor:HDMI-A-1
workspace = 6, monitor:HDMI-A-1

workspace = 7, monitor:eDP-1
